=== ozzman02/JavaWebServices/patient-xml/Patient.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Patient"
	xmlns:tns="http://www.example.org/Patient" elementFormDefault="qualified">
	
	<element name="patient" type="tns:Patient"></element>
	
	<complexType name="Patient">
		<sequence>
			<element name="id" type="tns:Id"></element>
			<element name="name" type="tns:String15Chars"></element>
			<element name="age" type="int"></element>
			<element name="dob" type="date"></element>
			<element name="email" type="string"></element>
			<element name="gender" type="tns:Gender"></element>
			<element name="phone" type="string"></element>
		</sequence>
	</complexType>
	
	<simpleType name="Id">
		<restriction base="int">
			<pattern value="[0-9]*"></pattern>
		</restriction>
	</simpleType>
	
	<simpleType name="String15Chars">
		<restriction base="string">
			<maxLength value="15"></maxLength>
		</restriction>
	</simpleType>
	
	<simpleType name="Gender">
		<restriction base="string">
			<enumeration value="M"></enumeration>
			<enumeration value="F"></enumeration>
		</restriction>
	</simpleType>
	
</schema>

=== ozzman02/JavaWebServices/patient-xml/Patient.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patient xmlns:tns="http://www.example.org/Patient"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Patient Patient.xsd ">
	<tns:id>1</tns:id>
	<tns:name>Oscar</tns:name>
	<tns:age>37</tns:age>
	<tns:dob>1982-07-10</tns:dob>
	<tns:email>osantamaria@gmail.com</tns:email>
	<tns:gender>M</tns:gender>
	<tns:phone>72962632</tns:phone>
</tns:patient>
